#!/bin/bash

##NECESSARY JOB SPECIFICATIONS
#SBATCH --job-name=Run_Main       #Set the job name
#SBATCH --time=2:00:00             #Set the wall clock limit
#SBATCH --nodes=1                 #Request 1 node
#SBATCH --ntasks-per-node=8       #Request 8 cores per node
#SBATCH --mem=8Gb                 #Request 8GB per node 
#SBATCH --output=main_out.%j      #Send stdout/err
#SBATCH --gres=gpu:1              #Request 1 GPU per node
#SBATCH --partition=gpu           #Request the GPU queue

ml purge
ml Miniconda3

cd $SCRATCH/Cifar10SimpleDLA/starter_code
echo
source activate SimpleDLA
echo
python main.py train ../Data/